const express = require('express');
const { auth, authorize } = require('../middleware/auth');
const controller = require('../controllers/adminController');
const router = express.Router();
router.use(auth, authorize('admin'));
router.get('/stats', controller.stats);
router.get('/rides', controller.listRides);
router.get('/captains', controller.listCaptains);
router.patch('/captains/:id/status', controller.updateCaptainStatus);
router.patch('/users/:id/status', controller.updateUserStatus);
module.exports = router;
