const mongoose = require('mongoose');
const Ride = require('../models/Ride');
const Captain = require('../models/Captain');
const { success } = require('../utils/response');
const { createRide, changeStatus } = require('../services/rideService');
const { startMatching, offerNextCaptain, claimNextCaptain, rejectCaptain, expireOffer } = require('../services/matchingService');
const { emitOffer, emitStatus } = require('../socket');
function bad(message,code='VALIDATION_ERROR',statusCode=400){const e=new Error(message);e.code=code;e.statusCode=statusCode;return e;}
function readPoint(value,name){const lat=Number(value?.lat),lng=Number(value?.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180)throw bad(`Invalid ${name} coordinates`,'INVALID_COORDINATES');return{lat,lng};}
async function pushOffer(rideId){const offer=await offerNextCaptain(rideId);if(offer)emitOffer(offer);return offer;}
async function create(req,res,next){try{const {serviceType,pickup,dropoff,pickupAddress='',dropoffAddress=''}=req.body;const ride=await createRide({customerId:req.user._id,serviceType,pickup:readPoint(pickup,'pickup'),dropoff:readPoint(dropoff,'dropoff'),pickupAddress,dropoffAddress});const matching=await startMatching(ride._id);const offer=await pushOffer(ride._id);return success(res,{ride:offer?.ride||matching.ride,offer:offer?{captainId:offer.captain._id,expiresAt:offer.expiresAt}:null},201);}catch(e){next(e);}}
async function getById(req,res,next){try{if(!mongoose.isValidObjectId(req.params.id))throw bad('Ride not found','RIDE_NOT_FOUND',404);const ride=await Ride.findById(req.params.id).populate('customer','name phone profile').populate({path:'captain',populate:{path:'user',select:'name phone profile'}});if(!ride)throw bad('Ride not found','RIDE_NOT_FOUND',404);const admin=req.user.role==='admin',customer=ride.customer._id.equals(req.user._id),captain=req.user.role==='captain'&&ride.captain?.user?._id?.equals(req.user._id);if(!admin&&!customer&&!captain)throw bad('You do not have access to this ride','FORBIDDEN',403);return success(res,ride);}catch(e){next(e);}}
async function accept(req,res,next){try{if(!mongoose.isValidObjectId(req.params.id))throw bad('Ride not found','RIDE_NOT_FOUND',404);const captain=await Captain.findOne({user:req.user._id,status:'active',availability:'busy'});if(!captain)throw bad('Captain has no active offer','CAPTAIN_NOT_AVAILABLE',409);const ride=await claimNextCaptain(req.params.id,captain._id);if(!ride)throw bad('Ride offer is expired or unavailable','RIDE_UNAVAILABLE',409);emitStatus(ride);return success(res,ride);}catch(e){next(e);}}
async function reject(req,res,next){try{const captain=await Captain.findOne({user:req.user._id});if(!captain)throw bad('Captain profile not found','CAPTAIN_NOT_FOUND',404);const ride=await rejectCaptain(req.params.id,captain._id);if(!ride)throw bad('Ride offer is no longer active','RIDE_UNAVAILABLE',409);const offer=await pushOffer(req.params.id);return success(res,{ride:offer?.ride||ride,offer:offer?{captainId:offer.captain._id,expiresAt:offer.expiresAt}:null});}catch(e){next(e);}}
async function timeout(req,res,next){try{const ride=await expireOffer(req.params.id);if(!ride)return success(res,null);const offer=await pushOffer(req.params.id);return success(res,{ride:offer?.ride||ride,offer:offer?{captainId:offer.captain._id,expiresAt:offer.expiresAt}:null});}catch(e){next(e);}}
async function captainAction(req,res,next){try{if(!mongoose.isValidObjectId(req.params.id))throw bad('Ride not found','RIDE_NOT_FOUND',404);const captain=await Captain.findOne({user:req.user._id});if(!captain)throw bad('Captain profile not found','CAPTAIN_NOT_FOUND',404);const ride=await Ride.findById(req.params.id);if(!ride||!ride.captain?.equals(captain._id))throw bad('Ride not found','RIDE_NOT_FOUND',404);const nextStatus={arriving:'captain_arriving',arrived:'captain_arrived',start:'trip_started',complete:'trip_completed'}[req.params.action];const updated=await changeStatus(ride,nextStatus);if(nextStatus==='trip_completed'||nextStatus==='cancelled')await Captain.updateOne({_id:captain._id,availability:'busy'},{$set:{availability:'online'}});emitStatus(updated);return success(res,updated);}catch(e){next(e);}}
async function cancel(req,res,next){try{if(!mongoose.isValidObjectId(req.params.id))throw bad('Ride not found','RIDE_NOT_FOUND',404);const ride=await Ride.findById(req.params.id);if(!ride)throw bad('Ride not found','RIDE_NOT_FOUND',404);const isCustomer=req.user.role==='customer'&&ride.customer.equals(req.user._id);let isCaptain=false;if(req.user.role==='captain'){const c=await Captain.findOne({user:req.user._id});isCaptain=!!c&&ride.captain?.equals(c._id);}if(req.user.role!=='admin'&&!isCustomer&&!isCaptain)throw bad('You do not have access to this ride','FORBIDDEN',403);const updated=await changeStatus(ride,'cancelled');updated.cancellation.cancelledBy=req.user.role;updated.cancellation.reason=String(req.body?.reason||'').trim().slice(0,300);updated.cancellation.cancelledAt=new Date();await updated.save();if(ride.captain)await Captain.updateOne({_id:ride.captain,availability:'busy'},{$set:{availability:'online'}});emitStatus(updated);return success(res,updated);}catch(e){next(e);}}
module.exports={create,getById,accept,reject,timeout,captainAction,cancel};
