const mongoose=require('mongoose');
const Ride=require('../models/Ride');
const Captain=require('../models/Captain');
const {success}=require('../utils/response');
const {createRide,changeStatus}=require('../services/rideService');
const {startMatching,offerNextCaptain,claimNextCaptain,rejectCaptain,expireOffer}=require('../services/matchingService');
const {createNotification}=require('../services/notificationService');
const {emitOffer,emitStatus}=require('../socket');
function bad(message,code='VALIDATION_ERROR',statusCode=400){const e=new Error(message);e.code=code;e.statusCode=statusCode;return e;}
function readPoint(value,name){const lat=Number(value?.lat),lng=Number(value?.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180)throw bad(`Invalid ${name} coordinates`,'INVALID_COORDINATES');return{lat,lng};}
async function notify(recipient,role,type,title,message,ride,data={}){try{return await createNotification({recipient,recipientRoleName:role,type,title,message,ride,data});}catch(e){console.error('Notification error:',e.message);return null;}}
async function notifyOffer(offer){if(!offer?.captain?.user)return;return notify(offer.captain.user,'captain','ride_requested','طلب رحلة جديد','يوجد طلب رحلة قريب منك.',offer.ride._id,{serviceType:offer.ride.serviceType,estimatedFare:offer.ride.estimatedFare,estimatedDistanceKm:offer.ride.estimatedDistanceKm,expiresAt:offer.expiresAt});}
async function pushOffer(id){const offer=await offerNextCaptain(id);if(offer){emitOffer(offer);await notifyOffer(offer);}return offer;}
async function create(req,res,next){try{const {serviceType,pickup,dropoff,pickupAddress='',dropoffAddress=''}=req.body;if(!['taxi','motorcycle','delivery'].includes(serviceType))throw bad('Invalid service type','INVALID_SERVICE_TYPE');const ride=await createRide({customerId:req.user._id,serviceType,pickup:readPoint(pickup,'pickup'),dropoff:readPoint(dropoff,'dropoff'),pickupAddress,dropoffAddress});const matching=await startMatching(ride._id);const offer=await pushOffer(ride._id);return success(res,{ride:offer?.ride||matching.ride,offer:offer?{captainId:offer.captain._id,expiresAt:offer.expiresAt}:null},201);}catch(e){next(e);}}
async function getById(req,res,next){try{if(!mongoose.isValidObjectId(req.params.id))throw bad('Ride not found','RIDE_NOT_FOUND',404);let ride=await Ride.findById(req.params.id);if(!ride)throw bad('Ride not found','RIDE_NOT_FOUND',404);const admin=req.user.role==='admin',customer=req.user.role==='customer'&&ride.customer.equals(req.user._id);let captain=false;if(req.user.role==='captain'){const c=await Captain.findOne({user:req.user._id}).select('_id');captain=!!c&&ride.captain?.equals(c._id);}if(!admin&&!customer&&!captain)throw bad('You do not have access to this ride','FORBIDDEN',403);if(customer&&ride.status==='searching'&&ride.matching?.offerExpiresAt&&ride.matching.offerExpiresAt<=new Date()){await expireOffer(ride._id);await pushOffer(ride._id);ride=await Ride.findById(ride._id);if(!ride)throw bad('Ride not found','RIDE_NOT_FOUND',404);}await ride.populate([{path:'customer',select:'name profile'},{path:'captain',populate:{path:'user',select:'name profile'}}]);return success(res,ride);}catch(e){next(e);}}
async function accept(req,res,next){try{if(!mongoose.isValidObjectId(req.params.id))throw bad('Ride not found','RIDE_NOT_FOUND',404);const captain=await Captain.findOne({user:req.user._id,status:'active',availability:'busy'});if(!captain)throw bad('Captain has no active offer','CAPTAIN_NOT_AVAILABLE',409);const ride=await claimNextCaptain(req.params.id,captain._id);if(!ride)throw bad('Ride offer is expired or unavailable','RIDE_UNAVAILABLE',409);await notify(ride.customer,'customer','ride_accepted','تم قبول الرحلة','الكابتن قبل طلبك وهو في طريقه إليك.',ride._id,{status:ride.status});emitStatus(ride);return success(res,ride);}catch(e){next(e);}}
async function reject(req,res,next){try{if(!mongoose.isValidObjectId(req.params.id))throw bad('Ride not found','RIDE_NOT_FOUND',404);const captain=await Captain.findOne({user:req.user._id});if(!captain)throw bad('Captain profile not found','CAPTAIN_NOT_FOUND',404);const ride=await rejectCaptain(req.params.id,captain._id);if(!ride)throw bad('Ride offer is no longer active','RIDE_UNAVAILABLE',409);const offer=await pushOffer(req.params.id);return success(res,{ride:offer?.ride||ride,offer:offer?{captainId:offer.captain._id,expiresAt:offer.expiresAt}:null});}catch(e){next(e);}}
async function timeout(req,res,next){try{if(!mongoose.isValidObjectId(req.params.id))throw bad('Ride not found','RIDE_NOT_FOUND',404);let captainId=null;if(req.user.role==='captain'){const captain=await Captain.findOne({user:req.user._id}).select('_id');if(!captain)throw bad('Captain profile not found','CAPTAIN_NOT_FOUND',404);captainId=captain._id;}const ride=await Ride.findOne({_id:req.params.id,status:'searching','matching.offerExpiresAt':{$lte:new Date()},...(captainId?{'matching.currentCaptain':captainId}:{})}).select('matching.currentCaptain');if(!ride)return success(res,null);const expired=await expireOffer(req.params.id);if(!expired)return success(res,null);const offer=await pushOffer(req.params.id);return success(res,{ride:offer?.ride||expired,offer:offer?{captainId:offer.captain._id,expiresAt:offer.expiresAt}:null});}catch(e){next(e);}}
async function captainAction(req,res,next){try{if(!mongoose.isValidObjectId(req.params.id))throw bad('Ride not found','RIDE_NOT_FOUND',404);const captain=await Captain.findOne({user:req.user._id,status:'active'});if(!captain)throw bad('Captain profile not found','CAPTAIN_NOT_FOUND',404);const ride=await Ride.findById(req.params.id);if(!ride||!ride.captain?.equals(captain._id))throw bad('Ride not found','RIDE_NOT_FOUND',404);const nextStatus={arriving:'captain_arriving',arrived:'captain_arrived',start:'trip_started',complete:'trip_completed'}[req.params.action];if(!nextStatus)throw bad('Invalid captain action','INVALID_ACTION',400);const updated=await changeStatus(ride,nextStatus);const map={captain_arriving:['captain_arriving','الكابتن في الطريق','الكابتن تحرك باتجاه موقعك.'],captain_arrived:['captain_arrived','الكابتن وصل','الكابتن وصل إلى موقع الانطلاق.'],trip_started:['trip_started','بدأت الرحلة','تم بدء الرحلة بنجاح.'],trip_completed:['trip_completed','اكتملت الرحلة','تم إنهاء الرحلة بنجاح.']};const n=map[nextStatus];if(n)await notify(updated.customer,'customer',n[0],n[1],n[2],updated._id,{status:updated.status});if(nextStatus==='trip_completed')await Captain.updateOne({_id:captain._id,availability:'busy'},{$set:{availability:'online'}});emitStatus(updated);return success(res,updated);}catch(e){next(e);}}
async function cancel(req,res,next){try{if(!mongoose.isValidObjectId(req.params.id))throw bad('Ride not found','RIDE_NOT_FOUND',404);const ride=await Ride.findById(req.params.id);if(!ride)throw bad('Ride not found','RIDE_NOT_FOUND',404);const isCustomer=req.user.role==='customer'&&ride.customer.equals(req.user._id);let isCaptain=false;if(req.user.role==='captain'){const c=await Captain.findOne({user:req.user._id});isCaptain=!!c&&ride.captain?.equals(c._id);}if(req.user.role!=='admin'&&!isCustomer&&!isCaptain)throw bad('You do not have access to this ride','FORBIDDEN',403);const reason=String(req.body?.reason||'').trim().slice(0,300);const offeredCaptainId=ride.matching?.currentCaptain;const updated=await changeStatus(ride,'cancelled',{cancelledBy:req.user.role,reason});if(ride.captain)await Captain.updateOne({_id:ride.captain,availability:'busy'},{$set:{availability:'online'}});else if(offeredCaptainId)await Captain.updateOne({_id:offeredCaptainId,availability:'busy'},{$set:{availability:'online'}});if(isCustomer&&ride.captain){const c=await Captain.findById(ride.captain).select('user');if(c?.user)await notify(c.user,'captain','ride_cancelled','تم إلغاء الرحلة','قام الزبون بإلغاء الرحلة.',updated._id);}else if(isCaptain)await notify(ride.customer,'customer','ride_cancelled','تم إلغاء الرحلة','قام الكابتن بإلغاء الرحلة.',updated._id);emitStatus(updated);return success(res,updated);}catch(e){next(e);}}
module.exports={create,getById,accept,reject,timeout,captainAction,cancel};
